# Generated by Django 4.2.1 on 2023-05-20 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be entered in the format: '+999999999'. Up to 10 digits allowed.",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
            ),
        ),
    ]
